name: Auto Update M3U Playlist

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Execute Permission for Script
        run: chmod +x autorun.sh

      - name: Run autorun.sh Script
        run: ./autorun.sh

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add youtube.m3u
          git commit -m "Auto-update M3U playlist"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
