name: M3U generator

on:
  schedule:
    - cron: '0 0/2 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main
        run: |
          pwd
          chmod +x autorun.sh
          ./autorun.sh

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git commit -m "links are updated" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
          
